export enum AppActTypes {
    setUpdatingStatus = 'setUpdatingStatus',
    setNotifications = 'setNotifications',
    setOnlyImportant = 'setOnlyImportant',
    setOnlyToday = 'setOnlyToday',
    setShowCompleted = 'setShowCompleted',
    setShowCancel = 'setShowCancel',
    setShowOverdue = 'setShowOverdue',
    setDefault = 'setDefault',
    addError = 'addError',
    addMessage = 'addMessage',
    removeLastError = 'removeLastError',
    removeLastMessage = 'removeLastMessage',
    clearErrors = 'clearErrors',
    clearMessages = 'clearMessages',
}